name: Run Lint Checks

on:
  workflow_call:

  pull_request:
    branches:
      - '**'

  merge_group:
    types: [checks_requested]

jobs:
  run-swiftlint:
    name: Run SwiftLint
    runs-on: macos-14
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v4

    - name: Find modified Swift files and lint them
      run: |
        BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
        FEATURE_BRANCH="${{ github.event.pull_request.head.ref }}"

        # Get list of changed Swift files as an array
        modified_files=($(git diff --name-only origin/$BASE_BRANCH...$FEATURE_BRANCH -- '*.swift'))
        readonly modified_files

        if [ -z "$modified_files" ]; then
            echo "No Swift files were changed. Linter won't run."
            exit 0
        fi

        files_argument=""
        for i in "${modified_files[@]}"; do
            files_argument="$files_argument $i"
        done

        echo "Base branch: $BASE_BRANCH"
        echo "Feature branch: $FEATURE_BRANCH"
        echo "Modified files: $files_argument"

        # Run SwiftLint on the changed files
        echo "Executing: ./bin/swiftlint/run-swiftlint.sh -i $files_argument"
        ./bin/swiftlint/run-swiftlint.sh -i "$files_argument"
